### ISSUE TITLE
If the prediction horizon is less than the number of states, a segmentation fault occurs.

### ISSUE THREAD

**Issue by sm3304love** [Kotakku/simple_casadi_mpc#1]
Hello, I am a student trying to implement MPC based on your library. I would like to express my gratitude to you for creating a library that made it easy to use casadi, which made it easy to implement mpc.

The question I would like to ask in the repository is that if the predict horizon is smaller than the number of states, nx, a segment error occurs.

The part where the problem occurs is in the code below that declares the MPC class in simple_casadi_mpc.hpp.
```
for (auto l = 0; l < nx; l++)
  {
         lbw_.push_back(x_bounds[nx - 1].first[l]);
         ubw_.push_back(x_bounds[nx - 1].second[l]);
  }
```
I would like to ask whether the number of repetitions in the for statement in the above code should be predict horizon N, not nx.

**Comment by Kotakku** [comment]
Hello, thank you for using simple_casadi_mpc.

The code in the relevant section should be N for predict horizon, not nx.
I will fix it immediately. Thank you!

**Comment by sm3304love** [comment]
Hello, thank you for answering my questions. 
I have another question! 
Do I need to modify the header file to add data received from the sensor to the stage cost and terminal cost functions?

**Comment by Kotakku** [comment]
Yes, the header file must be changed to include a value that changes with each control loop in the cost function.
Bug fixes and functionality additions. Please check it out!

**Comment by Kotakku** [comment]
Perhaps by changing the code in ```cartpole_mpc_example.cpp``` you can achieve what you want to do.

declare parameter
```c++
x_ref = parameter("x_ref", 4, 1);
```
set parameter
```c++
    casadi::DMDict param_list;
    double target_pos = -0.5;
    param_list["x_ref"] = {target_pos, M_PI, 0, 0};
```
solve MPC with parameter
```c++
Eigen::VectorXd u = mpc.solve(x, param_list);
```

**Comment by sm3304love** [comment]
hello! I confirmed that the code has been modified. Thanks for your help.

If I want to use the location of external obstacles in inequality constraints, I need to modify ```simple_casadi_mpc.hpp``` right?

**Comment by Kotakku** [comment]
External obstacles can be declared by inheriting from the ```simple_casadi_mpc::Problem``` class.
The ```obstacle1``` and ```obstacle2``` functions in ```diff_drive_mpc_example.cpp``` correspond to this. Please check it out!

**Comment by Kotakku** [comment]
I am closing this issue because the content of the title has been fixed.
If you have any other questions about usage or bugs, please feel free to open a new issue.
